name: CD - Docker Build & Push (Statique)

on:
  push:
    branches: ["main"] # D√©clencher directement sur push vers main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Lecture du code source
      packages: write #
    steps:
      - name: üì• Checkout code
        uses: actions/checkout@v4

      - name: üîë Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: üê≥ Build Docker image
        # Utilise le nouveau nom d'image
        run: docker build -t ghcr.io/ryandevgithub/site-vitrine-web-catalyste:latest .

      - name: üì§ Push Docker image
        run: docker push ghcr.io/ryandevgithub/site-vitrine-web-catalyste:latest

  deploy:
    name: "üöÄ Deploy to VPS"
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: üöÄ Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT}}
          script: |
            CONTAINER_NAME="site-vitrine-web-catalyste"
            IMAGE_NAME="ghcr.io/ryandevgithub/$CONTAINER_NAME:latest"
             echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin 
             
               docker stop $CONTAINER_NAME || true
               docker rm $CONTAINER_NAME || true
               
               # 3. Pull la derni√®re image (Ceci ne sera plus denied !)
               docker pull $IMAGE_NAME
               
               # 4. Run nouveau conteneur
               docker run -d \
                 --name $CONTAINER_NAME \
                 --restart unless-stopped \
                 -p 8084:80 \
                 $IMAGE_NAME
               
               # 5. BONNE PRATIQUE : D√©connexion apr√®s usage (S√©curit√©)
               docker logout ghcr.io

               # 6. V√©rifie que le conteneur est bien lanc√©
               docker ps -f name=$CONTAINER_NAME
